### ISSUE TITLE
No audio files generated

### ISSUE THREAD

**Issue by joshuatw** [r9y9/gantts#11]
Hi there,

After running the command (./vc_demo.sh vc_gan_test ~/data/cmu_arctic/), 'checkpoints' are created but no audio files in the './generated' folder. Here followings are my log shown 'Finished!'

90%|
 | 179/200 [21:24<02:30,  7.18s/it]('Saved checkpoint:', 'checkpoints/checkpoint_epoch180_Generator.pth')
('Saved checkpoint:', 'checkpoints/checkpoint_epoch180_Discriminator.pth')
 94%|
 | 189/200 [22:35<01:18,  7.17s/it]('Saved checkpoint:', 'checkpoints/checkpoint_epoch190_Generator.pth')
('Saved checkpoint:', 'checkpoints/checkpoint_epoch190_Discriminator.pth')
100%|
 [23:48<00:07,  7.18s/it]('Saved checkpoint:', 'checkpoints/checkpoint_epoch200_Generator.pth')
('Saved checkpoint:', 'checkpoints/checkpoint_epoch200_Discriminator.pth')
100%|
[23:55<00:00,  7.18s/it]
('Saved checkpoint:', 'checkpoints/checkpoint_epoch200_Generator.pth')
('Saved checkpoint:', 'checkpoints/checkpoint_epoch200_Discriminator.pth')
Finished!

**Comment by r9y9** [comment]
That's strange. Did you see any other messages? Could you try the following command directly?

```
python evaluation_vc.py \
    ./checkpoints/baseline/checkpoint_epoch200_Generator.pth \
    ./data/cmu_arctic_vc \
    ~/data/cmu_arctic/cmu_us_clb_arctic/wav \
    ./generated/baseline \
    --diffvc
```

https://github.com/r9y9/gantts/blob/8111e255fb65ded1f0361c18c1a7e5c4c13ad840/vc_demo.sh#L42-L48

**Comment by joshuatw** [comment]
The result of running your command can lead to generated audio files in the './generated' folder eventually. Thank you!

However, according to the Usage of 'evaluation.py', which shows 'usage: evaluation_vc.py [options] <checkpoint> <data_dir> <wav_dir> <outputs_dir', but how about '--diffvc' command?

**Comment by r9y9** [comment]
See https://github.com/r9y9/gantts/issues/7#issuecomment-345490741.  Paper: https://www.researchgate.net/publication/287247914_Statistical_singing_voice_conversion_with_direct_waveform_modification_based_on_the_spectrum_differential

**Comment by Alexander-flyer** [comment]
Maybe you can update the code and try again.
The author have modified somewhere , and I think it's related to the question.
And....You'd better to provide as exhaustive information as possible, such as log information, and in addition you may find problems in the process of viewing the log.

**Comment by joshuatw** [comment]
Thanks a lot for the sharing. It succeeded after my trying again days ago.
