### ISSUE TITLE
Remind: the function 'adjast_frame_lengths' in nnmnkwii have been replaced to 'adjust_frame_lengths'

### ISSUE THREAD

**Issue by Alexander-flyer** [r9y9/gantts#13]
when call 'vc_demo.sh' , one thing should be take care for : 

`x, y = P.adjast_frame_lengths(x, y, pad=True, divisible_by=2)`

This line in 'prepare_features_vc.py' should been modified to 'adjust_frame_lengths', cause the function name in nnmnkwii has been changed.

**Comment by r9y9** [comment]
Thank you! FIxed
