### ISSUE TITLE
*** Error in `python': corrupted size vs. prev_size: 0x00007f1f7031bf00 ***

### ISSUE THREAD

**Issue by kindleton** [r9y9/gantts#14]
Hey @r9y9,
I am trying to run tts_demo. My environment is in Python 3.6
I am getting the following error, despite reducing the batch as suggested in #3 
Do you think it could be because of Python version? Can you suggest some steps that I should try to make the demo run ?

![image](https://user-images.githubusercontent.com/7459533/36416406-f736a966-164e-11e8-9815-6d7a251a891a.png)

**Comment by kindleton** [comment]
this solved my issue:
`sudo apt-get install libtcmalloc-minimal4`
`export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"`

**Comment by kratsg** [comment]
> this solved my issue:
> `sudo apt-get install libtcmalloc-minimal4`
> `export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"`

Can you provide some information on how you got those two magical lines?

**Comment by vishwa91** [comment]
I had a similar issue, though not for this package. Does anyone have any clue about why it works?

**Comment by banahdang** [comment]
oh my god. Thank you so much!!! This solved my issue.
For the note I leave my setup.

Rpi 3B+ / python 2.7 / audio-streaming with Sounddevice module

> this solved my issue:
> `sudo apt-get install libtcmalloc-minimal4`
> `export LD_PRELOAD="/usr/lib/libtcmalloc_minimal.so.4"`
