### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by yutaozuo** [r9y9/gantts#16]
I run the vc_demo.sh and it occurs this problem.
Segmentation fault (core dumped).

Then i use gdb to locate this problem.
Type "apropos word" to search for commands related to "word"...
"/home/xjl910940173/yutao/gantts-master/./vc_demo.sh": not in executable format: File format not recognized
[New LWP 2548]
Core was generated by `python3 train.py --hparams_name=vc --max_files=500 --w_d=0 --hparams=nepoch=200'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd829c0b5a7 in ?? ()

 I don't know how to fix. maybe you can help me .Thanks a lot.

**Comment by yuuSiVo** [comment]
I have same error
