### ISSUE TITLE
FileExistsError: [Errno 17] File exists: './checkpoints/jp_tts_order59/tts_duration/gan'

### ISSUE THREAD

**Issue by yuuSiVo** [r9y9/gantts#17]
こんにちは。日本語GAN TTSでFileExistsErrorが出て学習がスタートしません。我々開発チームでもあらゆる手段を尽くしましたが解決策が見つかりませんでした。どうすればいいのでしょうか

**Comment by r9y9** [comment]
```
rm -rf /checkpoints/jp_tts_order59
```

してから再度学習をスタートしてみてはいかがでしょうか。どのデータで、具体的に何をして、どのファイルのどのlineでエラーが起こったのか、より具体的に説明していただければ、別の提案もできるかもしれません。
