### ISSUE TITLE
gantts import __version__, but there is no file.

### ISSUE THREAD

**Issue by Hiroshiba** [r9y9/gantts#2]
In gantts.__init__, the code try to import __version__.
https://github.com/r9y9/gantts/blob/d1764f2970bd692067e8fc72577cbf9989f5f363/gantts/__init__.py#L4
But there is no file such as.

**Comment by r9y9** [comment]
```
pip install -e . 
```

or

```
python setup.py develop
```

should create `version.py`.  Relevant code is https://github.com/r9y9/gantts/blob/d1764f2970bd692067e8fc72577cbf9989f5f363/setup.py#L39-L43.

Let me know if the above commands not working property.

**Comment by Hiroshiba** [comment]
By running your code, __version__ was created. Thanks.

**Comment by sangramsingnk** [comment]
ModuleNotFoundError: No module named 'gantts.version'
