### ISSUE TITLE
Publish how much audio needed?

### ISSUE THREAD

**Issue by mathematiguy** [r9y9/gantts#21]
Hi there,

We're considering this for a dry run tts project with approx 300 hours of speech. Do you have any indication of how the model is likely to perform on this much data?

Even if you can state somewhere how many hours you had for the model you trained, that would be great.

Thanks.

**Comment by yuuSiVo** [comment]
GAN can get good results with less than 1 minute of audio data

**Comment by r9y9** [comment]
It really depends, but generally, I don't think so... :(
