### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'reduction'

### ISSUE THREAD

**Issue by caicaibins** [r9y9/gantts#22]
hey boys:
when I run the vc_demo train the model, it throw:
TypeError: __init__() got an unexpected keyword argument 'reduction'
how to fix it
THX

**Comment by yamachu** [comment]
Same issue has occurred.
In my env,
NG: torch-0.4.0-cp36-cp36m-manylinux1_x86_64.whl
OK: torch-0.4.1-cp36-cp36m-manylinux1_x86_64.whl

Try use PyTorch 0.4.1
