### ISSUE TITLE
RuntimeError: DFT length 4096 must be larger than time length 6240

### ISSUE THREAD

**Issue by yuuSiVo** [r9y9/gantts#25]
When trying to learn singing voice, this kind of error appears. Please tell me how to resolve

**Comment by yuuSiVo** [comment]
![image](https://user-images.githubusercontent.com/26115406/50571240-9aab4480-0de8-11e9-8600-281ce3a48dcd.png)

**Comment by r9y9** [comment]
Please set larger DFT length for modspec smoothing. See

- https://r9y9.github.io/nnmnkwii/latest/references/generated/nnmnkwii.preprocessing.modspec_smoothing.html#nnmnkwii.preprocessing.modspec_smoothing
- https://github.com/r9y9/gantts/blob/e661d1888ccefd0a51685da703e25105a2ea88f3/prepare_features_tts.py#L142-L143

or disable modspec smoothing https://github.com/r9y9/gantts/blob/e661d1888ccefd0a51685da703e25105a2ea88f3/hparams.py#L189.
