### ISSUE TITLE
Quality of voice conversion from female to male 

### ISSUE THREAD

**Issue by fxw915** [r9y9/gantts#26]
Hi all,
I tried out the voice conversion demo on the cmu_slt to cmu_bdl (female-male) dataset, yet it turns out the voice generated can hardly be recognized as a male. I run the Sprocket VC on the same datasets and it achieves a better generated audio with a voice closer to the target male speaker, though not as smooth as the gantts output. Is there anything we can do to improve this?
Thanks!

**Comment by mrgloom** [comment]
Can you provide examples for comparison?
