### ISSUE TITLE
OSError: [Errno 40] Too many levels of symbolic links:

### ISSUE THREAD

**Issue by caopan16** [r9y9/gantts#28]
I run the tts_demo.sh and it occurs this problem.  I don't know how to fix. maybe you can help me .Thanks a lot.

[luban@2d9ccf399183 gantts]$ ./tts_demo.sh
Experimental id:
Data dir: ./data/cmu_arctic_tts_order59
-1
----------
./nnmnkwii_gallery/data/slt_arctic_full_data/
./data/cmu_arctic_tts_order59
Traceback (most recent call last):
  File "prepare_features_tts.py", line 186, in <module>
    subphone_features=hp_duration.subphone_features)
  File "prepare_features_tts.py", line 45, in __init__
    hp_acoustic.question_path)
  File "/nfs/project/miniconda3/lib/python3.6/site-packages/nnmnkwii/io/hts.py", line 353, in load_question_set
    with open(qs_file_name) as f:
OSError: [Errno 40] Too many levels of symbolic links: '/nfs/cold_project/caopan_i/gantts/nnmnkwii_gallery/data/questions-radio_dnn_416.hed'

**Comment by r9y9** [comment]
Looks like this isn't a problem of our code. See https://stackoverflow.com/questions/30040308/mkvirtualenv-too-many-levels-of-symbolic-links for example.

**Comment by caopan16** [comment]
Thanks a lot . In fact, I always had this problem in the beginning. I don't know how to solve it.



------------------ 原始邮件 ------------------
发件人: "Ryuichi Yamamoto"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 下午2:03
收件人: "r9y9/gantts"<gantts@noreply.github.com>;
抄送: "草小妹"<815602984@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [r9y9/gantts] OSError: [Errno 40] Too many levels of symboliclinks: (#28)




Looks like this isn't a problem of our code. See https://stackoverflow.com/questions/30040308/mkvirtualenv-too-many-levels-of-symbolic-links for example.

**Comment by caopan16** [comment]
Thanks a lot . In fact, I always had this problem in the beginning. I don't know how to solve it. Maybe you can help me .Thanks a lot.



------------------ 原始邮件 ------------------
发件人: "Ryuichi Yamamoto"<notifications@github.com>;
发送时间: 2019年4月27日(星期六) 下午2:03
收件人: "r9y9/gantts"<gantts@noreply.github.com>;
抄送: "草小妹"<815602984@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [r9y9/gantts] OSError: [Errno 40] Too many levels of symboliclinks: (#28)




Looks like this isn't a problem of our code. See https://stackoverflow.com/questions/30040308/mkvirtualenv-too-many-levels-of-symbolic-links for example.
