### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory

### ISSUE THREAD

**Issue by syazw** [r9y9/gantts#3]
![au_er](https://user-images.githubusercontent.com/32951997/31950956-61956768-b90f-11e7-9b6a-948f9b300c87.png)

Hi @r9y9 , I got this error, I'm trying to fix this error but i didn't found. Hope u can help me out. Thanks

**Comment by r9y9** [comment]
Try smaller batch size. Default is 32 and it requires approx 3GB GPU memory.

https://github.com/r9y9/gantts/blob/f6f66b7cbdc6553a0b9880a6b9ccd60fae87b0a9/hparams.py#L160

EDIT: Sorry, default batch size for voice conversion was 20.

https://github.com/r9y9/gantts/blob/f6f66b7cbdc6553a0b9880a6b9ccd60fae87b0a9/hparams.py#L79
