### ISSUE TITLE
Feature extraction for TTS details

### ISSUE THREAD

**Issue by mrgloom** [r9y9/gantts#32]
I wonder why did you not used default setting like in pyworld demo? There is something specific for for TTS task?
https://github.com/JeremyCCHsu/Python-Wrapper-for-World-Vocoder/blob/master/demo/demo.py
https://github.com/r9y9/gantts/blob/master/prepare_features_tts.py#L108

**Comment by r9y9** [comment]
No reason it should be the same as the demo. Parameters definitely depend.
