### ISSUE TITLE
Issue when using my own data

### ISSUE THREAD

**Issue by khorshidisamira** [r9y9/gantts#38]
I have recorded my own voice and I want to use them instead of cmu files, however, I am getting the following error while running prepare_features_vc:
 python prepare_features_vc.py data/arctic_sam/ fem sam --dst_dir=./data/vc_sam/
Command line args:
 {'--dst_dir': './data/vc_sam/',
 '--help': False,
 '--max_files': '100',
 '--overwrite': False,
 '<DATA_ROOT>': 'data/arctic_sam/',
 '<source_speaker>': 'fem',
 '<target_speaker>': 'sam'}
Hyperparameters:
  adversarial_streams: [True]
  batch_size: 20
  cache_size: 1200
  discriminator: MLP
  discriminator_linguistic_condition: False
  discriminator_params: {'out_dim': 1, 'num_hidden': 2, 'dropout': 0.5, 'hidden_dim': 256, 'in_dim': 59, 'last_sigmoid': True}
  frame_period: 5
  generator: In2OutHighwayNet
  generator_add_noise: False
  generator_noise_dim: 200
  generator_params: {'out_dim': None, 'num_hidden': 3, 'static_dim': 59, 'hidden_dim': 512, 'in_dim': None, 'dropout': 0.5}
  has_dynamic_features: [True]
  lr_decay_epoch: 10
  lr_decay_schedule: False
  mask_nth_mgc_for_adv_loss: 0
  name: vc
  nepoch: 200
  num_workers: 1
  optimizer_d: Adagrad
  optimizer_d_params: {'lr': 0.01, 'weight_decay': 0}
  optimizer_g: Adagrad
  optimizer_g_params: {'lr': 0.01, 'weight_decay': 0}
  order: 59
  pin_memory: True
  stream_sizes: [177]
  windows: [(0, 0, array([1.])), (1, 1, array([-0.5,  0. ,  0.5])), (1, 1, array([ 1., -2.,  1.]))]
Traceback (most recent call last):
  File "prepare_features_vc.py", line 77, in <module>
    max_files=max_files))
  File "prepare_features_vc.py", line 40, in __init__
    max_files=max_files)
  File "/home/sakhors/voiceConv/env/lib/python3.5/site-packages/nnmnkwii/datasets/cmu_arctic.py", line 45, in __init__
    speaker, available_speakers))
ValueError: Unknown speaker 'fem'. It should be one of ['awb', 'bdl', 'clb', 'jmk', 'ksp', 'rms', 'slt']

**Comment by r9y9** [comment]
https://github.com/r9y9/gantts/blob/b1d09d25dfe1361d4e5b2e2215e6def39fb7718a/prepare_features_vc.py#L33-L37

It's because prepare_features_vc.py is written for cmu_arctic dataset. You will need to change the script according to your dataset.
