### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by syazw** [r9y9/gantts#4]
Hi @r9y9 .
How to solve this error? I used python 2.7.12 version.. Thanks for your help 
![error_ok](https://user-images.githubusercontent.com/32951997/32412852-28420fb4-c23f-11e7-9fd3-7a4d9a4fc256.png)

**Comment by r9y9** [comment]
Please use Python3 instead. As of now the repository doesn't support python2.

**Comment by syazw** [comment]
that's mean I need to upgrade my version to python 3? or just install alongside with 2.7.12? @r9y9

**Comment by r9y9** [comment]
Either is ok. You can have multiple versions of python. See https://anaconda.org/ for example.

**Comment by syazw** [comment]
thanks :)
I already change python version to 3.5.2 using nano ~/.bashrc. but when I tried running again the code it still give me this error. Thank yo you so much for your help @r9y9 
![error_ok](https://user-images.githubusercontent.com/32951997/32416478-a007a6fe-c284-11e7-9ac9-635cd5d58b50.png)

**Comment by r9y9** [comment]
Please make sure you are running python3. It seems you are running python2.

```
python -c "import sys; print(sys.version)"                                                                                                                                                      master 
3.6.1 |Anaconda custom (64-bit)| (default, May 11 2017, 13:09:58) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
```

**Comment by syazw** [comment]
I already check the python version. But it seems showed me the same error. Thanks for your help, i appreciated so much, @r9y9 

![again](https://user-images.githubusercontent.com/32951997/32432952-5272cc08-c314-11e7-83f8-203fb8e9a144.png)

**Comment by r9y9** [comment]
According to https://docs.python.org/3/library/os.html#os.makedirs, `os.makedirs` in python 3.6 should accept `exist_ok` argment.  I suspect your bash involves old python. Please make sure you are actually running python3 by adding snippet into python script as:

```py
import sys
assert sys.version[:3]  == "3.6"
```

**Comment by r9y9** [comment]
Also please paste log text directly, not screenshot images. It's difficult to copy and paste to me.

**Comment by r9y9** [comment]
I have added python2 support.

**Comment by syazw** [comment]
thanks @r9y9  for now its work :+1:
