### ISSUE TITLE
from cuda_functional import SRU ImportError: No module named 'cuda_functional'

### ISSUE THREAD

**Issue by yuuSiVo** [r9y9/gantts#40]
I have same issue 

File "/mnt/c/Users/python_2nd/Documents/gantts-jp/gantts/models.py", line 150, in __init__
    from cuda_functional import SRU
ImportError: No module named 'cuda_functional'

How can I solve it?

I installed all cuda enviroment and sru[cuda]

**Comment by kaveenkumar** [comment]
I have the same issue. Any solutions?
