### ISSUE TITLE
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

### ISSUE THREAD

**Issue by annisaabuhamid** [r9y9/gantts#5]
hello @r9y9,
i encountered the following error as i run the program. i read from other issues  you said that need to install python 3 and above. but is there any way or any code that i can change to remain in python 2.7

![screenshot_2017-11-06_23-16-26](https://user-images.githubusercontent.com/32840015/32447989-a01a65c2-c348-11e7-9898-c703060a8056.png)

**Comment by r9y9** [comment]
https://github.com/r9y9/gantts/commit/95450df1f8755b417291d428c29a3ee0a0aa9499 should fix py2 issues. Please update code and let me know if it works for you.

**Comment by annisaabuhamid** [comment]
Thank you. Until now it can run smoothly.

**Comment by r9y9** [comment]
Feel free to reopen if you find the same issue.
