### ISSUE TITLE
Issue when using different database other than SLT

### ISSUE THREAD

**Issue by raghadeepa** [r9y9/gantts#9]
SLT model built successfully, When I try with my own database, I am facing following error. I also tried keeping SLT directory intact and changed questionfile, wav, state and phone labels. I am getting same error. Is any thing hard coded internally?

mkdirs: data/dam_voice/Y_acoustic
Duration linguistic feature dim 576
Duration feature dim 5
Acoustic linguistic feature dim 585
Traceback (most recent call last):
  File "prepare_features_tts.py", line 237, in <module>
    print("Acoustic feature dim", Y_acoustic[0].shape[-1])
  File "/home/ram/installations/anaconda3/lib/python3.5/site-packages/nnmnkwii/datasets/__init__.py", line 126, in __getitem__
    *self.collected_files[idx])
TypeError: collect_features() takes 3 positional arguments but 3409 were given

**Comment by r9y9** [comment]
Umm, it should work for your own dataset. It seems there's something wrong with `collect_files`. Could you please make sure you are collecting wav/lab files correctly?

https://github.com/r9y9/gantts/blob/8111e255fb65ded1f0361c18c1a7e5c4c13ad840/prepare_features_tts.py#L75-L82

Please check if `len(files)` are the number of wav/lab files you have.

**Comment by raghadeepa** [comment]
You are absolutely right. There was a difference in the label and wav count. After fixing that, feature extraction is progressing well.

Thank you for your quick fix.

**Comment by r9y9** [comment]
Glad to hear that. BTW the error message is not very informative and I would like to fix it. If you can reproduce, please leave a comment, otherwise I will try to do if I get a chance.

**Comment by r9y9** [comment]
I've improved the error messages.
